### ISSUE TITLE
Ux improvements planned?

### ISSUE THREAD

**Issue by rheos** [brunoblock/oystermesh#1]
The key to this being useful will be a less technical user experience.   Will there be a client side integration built to work with this to make it feel more like dropbox?

**Comment by brunoblock** [comment]
Yes this is just the raw baseline protocol running, you can run oystermesh.js in passive mode and build any interface on top of it. This technical-looking page will be used to launch dapps, so it's like seeing the computer boot-up instead of the actual application.

I can build a dropbox-like interface but the baseline protocol doesn't work well as dropbox since the data will expire without any recommits or consistent pulling. Second layer solutions can build on-top of Oyster to provide data guarantees, like how the old Oyster used to build on-top of IOTA with broker nodes etc. Now Oyster is not the new decentralized dropbox but the new decentralized internet and economical digital currency.
