### ISSUE TITLE
Get Akoya

### ISSUE THREAD

**Issue by elkaddourisaid** [brunoblock/oystermesh#11]
Hi,

Is there any chance to get AKOYA?
I didn't follow the news about akoya and found out what's going on now.

SHL and PRL are already on MEW.

BR,
Said

**Comment by brunoblock** [comment]
Sorry I can't keep doing exceptions or else there will be millions of exceptions. If you had PRL/SHL in mew during the snapshot you will have received your AKYE. Otherwise you can send your grievances to the Opacity team who illegally stole Oyster property (subreddit and twitter) and are constantly trying to restrict news about Akoya, which has become a contributing factor to why so many people missed out on the airdrop. Honest and transparent!
