### ISSUE TITLE
Oyster ERC20 to Oyster MeshToken

### ISSUE THREAD

**Issue by ShinEth** [brunoblock/oystermesh#2]
Are there any plans on how/when you can convert the ERC20 Oyster to the Oyster token on the meshnet? Other than that: now that the mesh combines functionalities of both "PRL" and "SHL" how do you plan to integrate the different tokens in the mesh?

**Comment by brunoblock** [comment]
Yes there are plans, I am studying two ways to do it:

Option 1 is the original PRL/SHL tokens are made redeemable for mesh coins since the ERC20 burn function is sufficient for the transfer.

Option 2 is that PRLMESH will be airdropped to PRL/SHL token holders as a unified token that is matched in supply parity to the actual mesh coin.

From there the ERC20 tokens can be converted to the mesh coins via a centralized gateway (relatively simple). I am planning on programming a basic market system for the mesh coin, but may also allow mesh coins to be converted back to ERC20 tokens as desired to facilitate trading volume on dexes (this would only happen with Option 2).
